### ISSUE TITLE
I like black. Can I have a black colour pallette plskthx?

### ISSUE THREAD

**Issue by KathyReid** [timrandall/front-end-framework#14]
Blacks, glorious blacks, warm blacks and cool, blacks just rule!

**Comment by KathyReid** [comment]
Also useful for high visibility - #a11y thinking

**Comment by timrandall** [comment]
Hi Kathy,

I have a greyscale palette. Is this what you're after? https://collaborate.deakin.edu.au/initiative/DCoE/Design-Code/SitePages/Colours.aspx

**Comment by KathyReid** [comment]
Lovely! Let's close the issue :+1:
